/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hat-transformed.glb --transform 
Files: hat-transformed.glb [227.05KB] > /Users/an/Documents/Projects/freeCodeCamp/portfolio-page-tutorial/public/models/hat-transformed-transformed.glb [226KB] (0%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hat-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} position={[0, -3.867, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/hat-transformed-transformed.glb')
